export enum LOGIN_REPONSE_CODE {
    LOGIN_SUCCESSFULL = 1,
    LOGIN_FAILED_WRONG_CHECKSUM = 2,
    LOGIN_FAILED_NOT_REGISTERED = 3,
    LOGIN_FAILED_INTERNAL_ERROR = 4
}

export enum REGISTER_REPONSE_CODE {
    REGISTRATION_SUCCESSFULL = 1,
    REGISTRATION_FAILED_ALREADY_REGISTERED = 2
}